POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
  "name": "User Nice 3",
  "email": "ggg@g.com",
  "password": "1234556"
}


POST http://localhost:8080/users/token HTTP/1.1
Content-Type: application/json

{
  "email": "ggg@g.com",
  "password": "1234556"
}
